pull_request_rules:
  - name: automatically merge steward's PRs
    conditions:
      - author=keynmol-steward[bot]
      - or:
        - body~=labels:.*semver-patch.*
        - body~=labels:.*semver-spec-patch.*
      - check-success=build
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions:
      - author=keynmol-steward[bot]
      - merged
    actions:
      delete_head_branch:
