name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install jsdom
        run: npm install jsdom@16.3.0    
      - name: Test
        run: sbt ci