name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Install jsdom
        run: npm install jsdom@20.0.0 

      - name: Test
        run: sbt ci
